# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget_login(object):
    def setupUi(self, Widget_login):
        Widget_login.setObjectName("Widget_login")
        Widget_login.resize(468, 372)
        Widget_login.setMaximumSize(QtCore.QSize(570, 474))
        self.label_3 = QtWidgets.QLabel(Widget_login)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 321, 61))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(Widget_login)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 140, 234, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Widget_login)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 260, 195, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonBox_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.buttonBox_2.setFont(font)
        self.buttonBox_2.setObjectName("buttonBox_2")
        self.horizontalLayout.addWidget(self.buttonBox_2)
        self.buttonBox = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Widget_login)
        QtCore.QMetaObject.connectSlotsByName(Widget_login)

    def retranslateUi(self, Widget_login):
        _translate = QtCore.QCoreApplication.translate
        Widget_login.setWindowTitle(_translate("Widget_login", "Form"))
        self.label_3.setText(_translate("Widget_login", "<html><head/><body><p><span style=\" font-size:28pt;\">图书管理系统</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("Widget_login", "学生"))
        self.comboBox.setItemText(1, _translate("Widget_login", "学生管理员"))
        self.comboBox.setItemText(2, _translate("Widget_login", "图书管理员"))
        self.comboBox.setItemText(3, _translate("Widget_login", "系统管理员"))
        self.label.setText(_translate("Widget_login", "用户名"))
        self.label_2.setText(_translate("Widget_login", "密码"))
        self.buttonBox_2.setText(_translate("Widget_login", "登录"))
        self.buttonBox.setText(_translate("Widget_login", "退出"))
