# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_manager_book.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_manager_book(object):
    def setupUi(self, MainWindow_manager_book):
        MainWindow_manager_book.setObjectName("MainWindow_manager_book")
        MainWindow_manager_book.resize(720, 600)
        MainWindow_manager_book.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        MainWindow_manager_book.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow_manager_book)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 171, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(130, 510, 129, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 510, 129, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 60, 71, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 60, 71, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 60, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(30, 100, 661, 391))
        self.tableView.setObjectName("tableView")
        MainWindow_manager_book.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_manager_book)
        self.statusbar.setObjectName("statusbar")
        MainWindow_manager_book.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow_manager_book)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 28))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow_manager_book.setMenuBar(self.menubar)
        self.action1_1 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action1_1.setFont(font)
        self.action1_1.setObjectName("action1_1")
        self.action2_1 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action2_1.setFont(font)
        self.action2_1.setObjectName("action2_1")
        self.action3_1 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action3_1.setFont(font)
        self.action3_1.setObjectName("action3_1")
        self.action1 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action1.setFont(font)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action2.setFont(font)
        self.action2.setObjectName("action2")
        self.action = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow_manager_book)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow_manager_book)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_manager_book)

    def retranslateUi(self, MainWindow_manager_book):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_manager_book.setWindowTitle(_translate("MainWindow_manager_book", "MainWindow"))
        self.label.setText(_translate("MainWindow_manager_book", "图书管理"))
        self.pushButton.setText(_translate("MainWindow_manager_book", "图书信息维护"))
        self.pushButton_2.setText(_translate("MainWindow_manager_book", "批量导入图书"))
        self.comboBox.setItemText(0, _translate("MainWindow_manager_book", "书号"))
        self.comboBox.setItemText(1, _translate("MainWindow_manager_book", "书名"))
        self.comboBox.setItemText(2, _translate("MainWindow_manager_book", "作者"))
        self.comboBox.setItemText(3, _translate("MainWindow_manager_book", "总数"))
        self.pushButton_3.setText(_translate("MainWindow_manager_book", "查询"))
        self.menu.setTitle(_translate("MainWindow_manager_book", "设置"))
        self.action1_1.setText(_translate("MainWindow_manager_book", "个人借阅查询"))
        self.action2_1.setText(_translate("MainWindow_manager_book", "图书借阅"))
        self.action3_1.setText(_translate("MainWindow_manager_book", "图书归还"))
        self.action1.setText(_translate("MainWindow_manager_book", "借阅排行"))
        self.action2.setText(_translate("MainWindow_manager_book", "图书搜索"))
        self.action.setText(_translate("MainWindow_manager_book", "密码更改"))
        self.action_2.setText(_translate("MainWindow_manager_book", "注销"))
