# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_manager_sys.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_manager_sys(object):
    def setupUi(self, MainWindow_manager_sys):
        MainWindow_manager_sys.setObjectName("MainWindow_manager_sys")
        MainWindow_manager_sys.resize(720, 600)
        MainWindow_manager_sys.setMaximumSize(QtCore.QSize(800, 600))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        MainWindow_manager_sys.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow_manager_sys)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 171, 30))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 510, 129, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 510, 129, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 510, 149, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 60, 176, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 100, 71, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 100, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(30, 140, 661, 351))
        self.tableView.setObjectName("tableView")
        MainWindow_manager_sys.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_manager_sys)
        self.statusbar.setObjectName("statusbar")
        MainWindow_manager_sys.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow_manager_sys)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 28))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        MainWindow_manager_sys.setMenuBar(self.menubar)
        self.action1_1 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action1_1.setFont(font)
        self.action1_1.setObjectName("action1_1")
        self.action2_1 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action2_1.setFont(font)
        self.action2_1.setObjectName("action2_1")
        self.action3_1 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action3_1.setFont(font)
        self.action3_1.setObjectName("action3_1")
        self.action1 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action1.setFont(font)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action2.setFont(font)
        self.action2.setObjectName("action2")
        self.action = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow_manager_sys)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.menu.addSeparator()
        self.menu.addAction(self.action)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow_manager_sys)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_manager_sys)

    def retranslateUi(self, MainWindow_manager_sys):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_manager_sys.setWindowTitle(_translate("MainWindow_manager_sys", "MainWindow"))
        self.label.setText(_translate("MainWindow_manager_sys", "系统管理"))
        self.pushButton.setText(_translate("MainWindow_manager_sys", "管理员添加"))
        self.pushButton_2.setText(_translate("MainWindow_manager_sys", "管理员删除"))
        self.pushButton_3.setText(_translate("MainWindow_manager_sys", "管理员信息更改"))
        self.comboBox.setItemText(0, _translate("MainWindow_manager_sys", "学生管理员-工号"))
        self.comboBox.setItemText(1, _translate("MainWindow_manager_sys", "学生管理员-姓名"))
        self.comboBox.setItemText(2, _translate("MainWindow_manager_sys", "图书管理员-工号"))
        self.comboBox.setItemText(3, _translate("MainWindow_manager_sys", "图书管理员-姓名"))
        self.pushButton_4.setText(_translate("MainWindow_manager_sys", "查询"))
        self.menu.setTitle(_translate("MainWindow_manager_sys", "设置"))
        self.action1_1.setText(_translate("MainWindow_manager_sys", "个人借阅查询"))
        self.action2_1.setText(_translate("MainWindow_manager_sys", "图书借阅"))
        self.action3_1.setText(_translate("MainWindow_manager_sys", "图书归还"))
        self.action1.setText(_translate("MainWindow_manager_sys", "借阅排行"))
        self.action2.setText(_translate("MainWindow_manager_sys", "图书搜索"))
        self.action.setText(_translate("MainWindow_manager_sys", "密码更改"))
        self.action_2.setText(_translate("MainWindow_manager_sys", "注销"))
